---
- name: Verify
  hosts: all

  tasks:
    - name: Gather service facts
      service_facts:

    - debug:
       msg: "{{ ansible_facts.services }}"

    - name: Verify that rngd is running
      assert:
        that: "ansible_facts.services['{{ item }}'] is defined and ansible_facts.services['{{ item }}'].state == 'running'"
      with_items:
        - rngd.service